#include <vex.h>

extern vex::brain myBrain;
extern vex::controller myController;
#define FIRST_MOVE_DISTANCE 300
#define FIRST_TURN_DEGREE 300
#define SECOND_MOVE_DISTANCE 300
#define SECOND_TURN_DEGREE 300
#define THIRD_MOVE_DISTANCE 300
#define THIRD_TURN_DEGREE 300
#define FOURTH_MOVE_DISTANCE 300
#define FOURTH_TURN_DEGREE 300
#define FIFTH_MOVE_DISTANCE 300
#define FIFTH_TURN_DEGREE 300
#define SIXTH_MOVE_DISTANCE 300
#define SIXTH_TURN_DEGREE 300
#define SEVENTH_MOVE_DISTANCE 300
#define SEVENTH_TURN_DEGREE 300

#define SPEEDAUTO 50